# Generated by Django 4.0.3 on 2022-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_teacher_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='report_status',
            field=models.BooleanField(default=False, verbose_name='Отчет сдан/несдан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.CharField(blank=True, max_length=20, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='student',
            name='theme',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='students_list',
            field=models.TextField(default=False, verbose_name='Студенты сдавшие отчёты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=10, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialisation',
            field=models.CharField(blank=True, max_length=80, verbose_name='Направление'),
        ),
    ]
